[package]
name = 'uuid'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'uuid'

[dependencies]
extendr-api = { git = 'https://github.com/extendr/extendr' }
derive_more = "0.99"
uuid = {version = "1.1.2", features = ["v1", "v3", "v4", "v5", "fast-rng"]}
rayon = "1.5.3"