# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_uuid_wrappers", use_symbols = TRUE, package_name = "uuid")

#' @docType package
#' @usage NULL
#' @useDynLib uuid, .registration = TRUE
NULL

#' Generate uuid
#' @export
uuid_ <- function(n, version) .Call(wrap__uuid_, n, version)

